/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

/**
 *
 * @author ihormelashchenko
 */
public class MenuScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public MenuScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        amendInformationButton = new javax.swing.JButton();
        requestUnenrollmentButton = new javax.swing.JButton();
        topUpCampusCreditButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        welcomeMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");
        setName("LoginScreen"); // NOI18N
        setResizable(false);

        headingLabel.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        headingLabel.setText("Student Management System");

        amendInformationButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        amendInformationButton.setText("Amend Information");
        amendInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amendInformationButtonActionPerformed(evt);
            }
        });

        requestUnenrollmentButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        requestUnenrollmentButton.setText("Request Unenrollment");
        requestUnenrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestUnenrollmentButtonActionPerformed(evt);
            }
        });

        topUpCampusCreditButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        topUpCampusCreditButton.setText("Top Up Campus Credit");
        topUpCampusCreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topUpCampusCreditButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        welcomeMessageLabel.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        welcomeMessageLabel.setText("welcomeMessageLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amendInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(requestUnenrollmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topUpCampusCreditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeMessageLabel)))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeMessageLabel)
                .addGap(27, 27, 27)
                .addComponent(headingLabel)
                .addGap(18, 18, 18)
                .addComponent(amendInformationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestUnenrollmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topUpCampusCreditButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amendInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amendInformationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amendInformationButtonActionPerformed

    private void requestUnenrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestUnenrollmentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestUnenrollmentButtonActionPerformed

    private void topUpCampusCreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topUpCampusCreditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topUpCampusCreditButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amendInformationButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton requestUnenrollmentButton;
    private javax.swing.JButton topUpCampusCreditButton;
    private javax.swing.JLabel welcomeMessageLabel;
    // End of variables declaration//GEN-END:variables
}
